### ISSUE TITLE
Falsche AC Werte

### ISSUE THREAD

**Issue by PVMainz** [h4ckst0ck/dbus-solaredge#3]
Hallo,
danke für das tolle Python Skript. Die Installation hat geklappt. Allerdings wird der AC Load nicht korrekt errechnet.
Ich habe folgenden Aufbau:
2 PV Inverter (Fronius und Solaredge), ein Energymeter (Solaredge), ein Pi 4 mit Venus OS.
Der Pi ist mit der Beta 2.90 versehen und hat den Fronius auch brav erkannt.
Für Solaredge habe ich dieses Skript installiert. Es kommen die richtigen Grid Werte rein, die Produktion des Solaredge Wechselrichters wird auf 3 Phasen gleichmäßig aufgeteilt, jedoch ist der HD Wave 3680H nur einphasig. Die Summe des PV Inverters passt aber.
Bin über jede Hilfestellung dankbar.
Danke für den Support.
![venus os](https://user-images.githubusercontent.com/113619482/190441877-972a6d44-f603-4a19-a457-bf71f621c280.png)

**Comment by h4ckst0ck** [comment]
Ok, das Problem ist also, dass auf L2 und L3 beim PV-Wechselrichter 373W zeigt?
Ändere mal bitte in Zeile 159 und 160:
dbusservice['pvinverter.pv0']['/Ac/L2/Power'] = round(_get_signed_short(regs.registers[12]) * sf / 3, 2)
dbusservice['pvinverter.pv0']['/Ac/L3/Power'] = round(_get_signed_short(regs.registers[12]) * sf / 3, 2)

auf:
dbusservice['pvinverter.pv0']['/Ac/L2/Power'] = 0
dbusservice['pvinverter.pv0']['/Ac/L3/Power'] = 0

Wenn das noch nicht hilft auch die Einträge für Current und Voltage, aber nur bei den Einträge für den pvinterverter, nicht bei grid.
Sollte dass das Problem lösen, kann ich da mal eine Einstellung für Einphasige WR rein nehmen.

**Comment by PVMainz** [comment]
1000 Dank. Für L1 habe ich das Teilen durch 3 entfernt, L2 + L3 auf 0 gesetzt und nun passt es

**Comment by h4ckst0ck** [comment]
Ups, stimmt das /3 muss da selbstverständlich auch weg. Perfekt, mit der Erkenntnis kann ich mal einen Konfigurationsschalter einbauen. Danke fürs Bescheid geben!

**Comment by PVMainz** [comment]
Die Leistungswerte passen nun. 
Phase L2 und L§ bekommen noch V und A Werte rein. Ich vermute, die sollten besser auch 0 sein, oder?
Liebe Grüße, Tim
![venus_os](https://user-images.githubusercontent.com/113619482/190611101-040ae439-2b46-4945-a3df-da94eb1b89aa.png)

**Comment by h4ckst0ck** [comment]
Ja, das meinte ich mit "auch die Einträge für Current und Voltage" :)

**Comment by PVMainz** [comment]
Genullt. Jetzt passt es. Dank Dir!

**Comment by PVMainz** [comment]
Wenn man L2 + L§ nullt passt wieder AC Lasten nicht mehr. Wenn die Register gezogen werden passt es aber. Ich weiss nicht, ob das so sauber ist aber beobachte es jetzt mal.

**Comment by PVMainz** [comment]
Ich bräuchte noch mal Hilfe. Manchmal läuft es, dann stimmt es wieder nicht. Das Problem ist bei AC Last L2. Das wird mir manchmal als 0 angezeigt. Auf L1 liegt Solaredge, auf L2 ein Fronius Wechselrichter. Der Fronius wird selbsttätig erkannt und ist drin. Ich habe L2 ja in dem Skript genullt, stimmt deshalb die Berechnung nicht?

**Comment by h4ckst0ck** [comment]
Dann einfach nicht Nullen, sondern die Einträge komplett auskommentieren (# an den Anfang der Zeilen).

**Comment by PVMainz** [comment]
Super. Ich habe den zweiten Wechselrichter (Fronius) nicht auf L2 konfiguriert. Mit dem Auskommentieren von L2 und L3 kommen die Solaredge Werte ganz sauber rein und AC Lasten stimmt auch. Vielen Dank für das Skript.
