### ISSUE TITLE
Netzfrequenz

### ISSUE THREAD

**Issue by PVMainz** [h4ckst0ck/dbus-solaredge#4]
Hallo,
lässt sich per dbus auch die Netzfrequenz des Solaredge Meters auslesen?
LG, Tim

**Comment by h4ckst0ck** [comment]
Ja, ich denke schon. Ich sehe es mir heute Abend mal an. Interesse halber: Wozu genau wird die Information benötigt? Das ESS läuft ja auch so, die Netzfrequenz kann ja am Multiplus AC In gemessen werden.

**Comment by h4ckst0ck** [comment]
Es gibt im "grid" Service von Victron gar keinen Pfad dafür. Siehe https://github.com/victronenergy/venus/wiki/dbus

**Comment by PVMainz** [comment]
Ich habe noch keinen Multiplus *gg* Habe erst mal die Grid Werte und beide PV Anlagen an den Pi gehängt und geschaut, ob es läuft. Lieben Dank für die schnelle Info.
